spring:
  datasource:
    url: ${mysql_url}
#    url: jdbc:h2:tcp://localhost/~/example-todo # db 경로
    username: ${mysql_username}
    password: ${mysql_passward}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: select 1
    sql:
      init:
        platform: mysql

  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 시작 시 모든 table drop하고 새로 create / 개발 단계에서만 사용
    properties:
      hibernate:
        format_sql: true # 표시되는 sql 정렬
        order_by.default_null_ordering: last

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging.level:
  org.hibernate.SQL: debug # sql 표시

server:
  servlet:
    session:
      tracking-modes: cookie