spring:
  datasource:
    url: jdbc:h2:mem:todo # db 인메모리 사용
#    url: jdbc:h2:tcp://localhost/~/example-todo # db 경로
    username: sa
    password:
    driver-class-name: org.h2.Driver

  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 시작 시 모든 table drop하고 새로 create / 개발 단계에서만 사용
    properties:
      hibernate:
        format_sql: true # 표시되는 sql 정렬
        order_by.default_null_ordering: last

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging.level:
  org.hibernate.SQL: debug # sql 표시

server:
  servlet:
    session:
      tracking-modes: cookie